
Error message :
Traceback (most recent call last):
  File "d:\User\lubin\Documents\#Programmation\python\bot discord\yokai bot\script\main.py", line 770, in medallium
    classes_name = next(iter(yokai_list_brute))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration


- Nom d'utilisateur / id : __hubble/882241177578004542
- Heure de l'erreur : 2025-03-16 20:59:18
- Commande qui a caus√© l'erreur : medallium