
Error message :
Traceback (most recent call last):
  File "d:\User\lubin\Documents\#Programmation\python\bot discord\yokai bot\script\main.py", line 716, in medallium
    return await send_embed(ctx, inv_embed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\User\lubin\Documents\#Programmation\python\bot discord\yokai bot\script\main.py", line 135, in send_embed
    await ctx.send(embed=embed)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\context.py", line 1077, in send
    await self.interaction.response.send_message(**kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\interactions.py", line 855, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\webhook\async_.py", line 223, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.embeds.0.fields.0.value: Must be 1024 or fewer in length.


- Nom d'utilisateur / id : __hubble/882241177578004542
- Heure de l'erreur : 2025-03-14 19:16:40
- Commande qui a caus√© l'erreur : medallium